# Generated by Django 5.0.6 on 2024-06-27 08:21

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_content', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name='ssbuzzdevelopment-destination920a3c57-159760eh33ti9'), upload_to='images', verbose_name='media file')),
                ('banner_img', models.FileField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name='ssbuzzdevelopment-destination920a3c57-159760eh33ti9'), upload_to='images', verbose_name='media file')),
                ('draft_status', models.IntegerField(blank=True, null=True)),
                ('visibility', models.IntegerField(blank=True, default=1, null=True)),
                ('approve', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
